baseurl = "http://jillmunson.com/"
languageCode = "en-us"
title = "Jill Munson"

contentdir = "content"
publishdir = "./"
theme = "hugo-theme-casper"
canonifyurls = false
builddrafts = false
DisqusShortname = "jaemu"
[params]
  cover = "img/parade.jpg"
  logo = "img/noh8.jpg"
  author = "Jill Munson"
  authorlocation = "Irvine, CA"
  authorwebsite = "email: hello at (this domain)"
  description = "Dreams in console.log, can probably fix your web app, most definitely cannot fix your printer."
  bio= "Software Engineer, Twitch. Musings and opinions here are my own."
  googleAnalyticsUserID = "UA-60038362-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "jaemu"
  linkedin = "https://www.linkedin.com/in/jillianmunson"
  instagram = "msito"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "Home"
  weight = -140
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/post"

[[menu.main]]
  name = "Projects"
  weight = -120
  url = "/project"

[[menu.main]]
  name = "About"
  weight = -120
  url = "/about"

[[menu.main]]
  name = "WIT Meetups"
  weight = -120
  url = "/meetups"