baseurl = "http://jillmunson.com/"
languageCode = "en-us"
title = "Jill Munson"

contentdir = "content"
publishdir = "./"
theme = "hugo-theme-casper"
canonifyurls = false
[params]
  cover = "img/female_founders.jpg"
  logo = "img/me.jpg"
  author = "Jill Munson"
  authorlocation = "New York, NY"
  authorwebsite = "email: hello at (this domain)"
  description = "Software Engineer.  Seawolf.  Steve Ballmer is my spirit animal"
  bio= "Software Engineer | Seawolf | Corg-mom "
  googleAnalyticsUserID = "UA-60038362-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "jaemu"
  twitterName = "maykaynvwd"
  linkedin = "https://www.linkedin.com/in/jillianmunson"
  instagram = "msito"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "Home"
  weight = -140
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/post"

[[menu.main]]
  name = "Projects"
  weight = -120
  url = "/projects"

[[menu.main]]
  name = "About"
  weight = -120
  url = "/about"