baseurl = "http://jillmunson.com/"
languageCode = "en-us"
title = "Jill Munson - insert clever title here"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
[params]
  title = "Jill Munson - insert clever title here"
  description = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"
